#include <stdio.h>

int main() {
int numeros[10];
int pares = 0, impares = 0;

printf("Insira 10 números inteiros:\n");
for (int i = 0; i < 10; i++) {
    printf("Número %d: ", i + 1);
    scanf("%d", &numeros[i]);

    if (numeros[i] % 2 == 0) {
        pares++;
    } else {
        impares++;
    }
}

printf("Quantidade de números pares: %d\n", pares);
printf("Quantidade de números ímpares: %d\n", impares);

return 0;
}
